Dont treat jazzerjs as a fuzz target (#3931)
It's incorrect to do so. Also, the file extension (.node) breaks
ClusterFuzz very badly because CF thinks the "fuzz target" is missing.
Fixes:
https://pantheon.corp.google.com/errors/detail/CIqR3rOw3IDLzgE;service=;version=;filter=%5B%22nonetype%22%5D?project=clusterfuzz-external
```
AttributeError: 'NoneType' object has no attribute 'endswith'
.get_supporting_file ( /mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/bot/fuzzers/utils.py:151
```
Related: https://github.com/google/oss-fuzz/issues/11538