Revert import change
Importing the dependency at the beginning of the file
causes the integration test to fail with the following error

File "/android/clusterfuzz/src/clusterfuzz/_internal/base/utils.py", line 813, in <module>
  @memoize.wrap(memoize.FifoInMemory(1))
AttributeError: module 'clusterfuzz._internal.base.memoize' has no attribute 'wrap'