Added Debugging Logs: (#4130)
Logs have been added to debug and resolve the following issues:
1. AttributeError: 'NoneType' object has no attribute 'stdin'
2. Line is too long for a stacktrace