Swarming: Tag metrics with swarming runtime. (#5248)
Currently if we run fuzzing sessions on swarming, the metrics dont seem
to register those fuzzing hours correctly:
<img width="952" height="676" alt="image"
src="https://github.com/user-attachments/assets/024db79d-9a24-4b34-9591-c2a49904dc69"
/>
Note that the swarming fuzzing hours appear as empty: `runtime=`

- This PR adds swarming as a possible runtime
- Adds swarming in the error count metric
- Now that theres no circular dependency between `logs` <->
`environment` modules, i removed some methods that were previously
declared twice to avoid said circular dependency, now they are correctly
imported from a single module
- Also adds unit tests


## Tests performed
Changes present in dev since before the last `dev` branch reset(which is
around 22th of April).

#### Worth noting error logs in `dev` env:
Heres a list of logs that came to my attention:

There is a recurring PERMISSION_DENIED exception in the
testcase_manager.py. It specifically points to "Missing or insufficient
permissions" when calling the Datastore API via gRPC.
```
method: "_do_run_testcase_and_return_result_in_queue"
path: "/mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/bot/testcase_manager.py"
}
message: "Exception occurred while running run_testcase_and_return_result_in_queue.
Traceback (most recent call last):
  File "/mnt/scratch0/clusterfuzz/src/third_party/google/cloud/ndb/_datastore_api.py", line 98, in rpc_call
    result = yield rpc
             ^^^^^^^^^
	status = StatusCode.PERMISSION_DENIED
	details = "Missing or insufficient permissions."
	debug_error_string = "UNKNOWN:Error received "
>
```
Not related since we are not making any changes nor to auth or to the
data store api.

```
raise RuntimeError('Request to %s failed. Code: %d. Reason: %s' %
RuntimeError: Request to https://storage.googleapis.com....
<Error><Code>SignatureDoesNotMatch</Code><Message>Access denied.</Message><Details>The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method.</Details>
```
A weird error group, seems related to missing permissions or mismatch
across service accounts, may be worth looking, or may come from other
tests that someone is performing in dev

---------

Co-authored-by: Diego Jardon <37823380+jardondiego@users.noreply.github.com>