Fix showmap exception.
Fix incorrect code since read_data_from_file does not return
None and always return file to exist.

Will help to fix rare
```
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/scratch0/clusterfuzz/bot/inputs/fuzzer-testcases-disk/temp-45905/afl_showmap_output'
at read_data_from_file (/mnt/scratch0/clusterfuzz/src/python/bot/fuzzers/engine_common.py:536)
at get_file_features (/mnt/scratch0/clusterfuzz/src/python/bot/fuzzers/afl/launcher.py:1053)
at merge_corpus (/mnt/scratch0/clusterfuzz/src/python/bot/fuzzers/afl/launcher.py:1107)
at libfuzzerize_corpus (/mnt/scratch0/clusterfuzz/src/python/bot/fuzzers/afl/launcher.py:1176)
```