Prevent integer overflow by using int64 instead of int32 (#4184)
Fixes:
```
ValueError: Value out of range: 2148226322

at ._extract_coverage_information ( /mnt/scratch0/bots/oss-fuzz-linux-zone5-host-qp4x-2/clusterfuzz/src/clusterfuzz/_internal/bot/tasks/utasks/corpus_pruning_task.py:978 )
at .utask_main ( /mnt/scratch0/bots/oss-fuzz-linux-zone5-host-qp4x-2/clusterfuzz/src/clusterfuzz/_internal/bot/tasks/utasks/corpus_pruning_task.py:1029 )
```