Resolve AttributeError in issue_filer.py (#5154)
Safeguard the process of issue filing by ensuring the presence of
attributes within `Issue` variants before accessing them.

This issue occurs due to the changes made in #5074. #5074 adds debugging
logs, and one of the logs tries to access an attribute (`component_id`)
of a class (`Issue`), resulting in the following error:
**'Issue' object has no attribute 'component_id'**

This issue has blocked the issue filing process.

The current changes aim to resolve this issue using `getattr()`, which
checks if an attribute exists and only then accesses it.