Invoke blackbox fuzzers with Python 2 explicitly. (#1630)
* Invoke blackbox fuzzers with Python 2 explicitly.

* Break up oddly formatted line

* Temporarily disable this on Windows.

* Unconditionally encode directory name in remove_directory. (#1629)

* Don't upload corpus element bigger than 5 MB. (#1632)

* Speculative fix for Travis CI. (#1634)

* Fix LOAS auth in Python 3. (#1633)

* Python 3 docker fixes. (#1635)

* Revert shell.remove_directory utf-8 exception fixes. (#1636)

* Revert "Unconditionally encode directory name in remove_directory. (#1629)"

This reverts commit d6ab9e118cc927570932515c455b2d72887f3977.

* Revert "Fix exception due to incorrect var in shell.remove_directory. (#1626)"

This reverts commit 2e8c1d03e3040e436fff2553bc6c00c037350d63.

* Revert "Encode the file path before calling into shutil in remove_directory. (#1589)"

This reverts commit 3dd4a44d0e6ecc7b6ca51246e4140638389176e4.

* Speculative fix for missing exceptions. (#1637)

* Packaged peach requirements into zip (#1618)

* Fix file size check for upload check. (#1640)

The check need to check file on untrusted worker for OSS-Fuzz.

* Fix travis, migrate to python 3. (#1641)

* Exception fixes (#1643)

1. Skip adding traces in threads for now. Unblocks manage-vms cron on
chromium.
Traceback (most recent call last):
  File "third_party/webapp2.py", line 604, in dispatch
    return method(*args, **kwargs)
  File "/srv/libs/handler.py", line 96, in wrapper
    return func(self)
  File "/srv/handlers/cron/manage_vms.py", line 714, in get
    manager.update_clusters()
  File "/srv/handlers/cron/manage_vms.py", line 198, in update_clusters
    self.finish_updates()
  File "/srv/handlers/cron/manage_vms.py", line 183, in finish_updates
    update.result()
  File "/opt/python3.7/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/opt/python3.7/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/opt/python3.7/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/handlers/cron/manage_vms.py", line 224, in update_cluster
    if instance_template.exists():
  File "/srv/handlers/cron/helpers/bot_manager.py", line 109, in exists
    self.get()
  File "/srv/handlers/cron/helpers/bot_manager.py", line 283, in get
    result_proc=self._identity)
  File "python/base/retry.py", line 102, in _wrapper
    if not handle_retry(num_try, exception=e):
  File "python/base/retry.py", line 79, in handle_retry
    total=tries)
  File "python/metrics/logs.py", line 422, in log_error
    emit(logging.ERROR, message, exc_info=sys.exc_info(), **extras)
  File "python/metrics/logs.py", line 384, in emit
    _add_appengine_trace(all_extras)
  File "python/metrics/logs.py", line 341, in _add_appengine_trace
    request = webapp2.get_request()
  File "third_party/webapp2.py", line 1757, in get_request
    assert getattr(_local, 'request', None) is not None, _get_request_error
AssertionError: Request global variable is not set."

2. Don't exception in upload testcase when it does not exist. We would
later log_error in archive_testcase_and_dependencies_in_gcs. This is expected on google
instance.
IOError: [Errno 2] No such file or directory: u'/mnt/scratch0/clusterfuzz/bot/inputs/fuzzer-testcases/crash-da39a3ee5e6b4b0d3255bfef95601890afd80709'
at upload_testcase (/mnt/scratch0/clusterfuzz/src/python/bot/testcase_manager.py:421)
at do_engine_fuzzing (/mnt/scratch0/clusterfuzz/src/python/bot/tasks/fuzz_task.py:1613)
at run (/mnt/scratch0/clusterfuzz/src/python/bot/tasks/fuzz_task.py:1881)
at execute_task (/mnt/scratch0/clusterfuzz/src/python/bot/tasks/fuzz_task.py:1961)
at run_command (/mnt/scratch0/clusterfuzz/src/python/bot/tasks/commands.py:204)
at process_command (/mnt/scratch0/clusterfuzz/src/python/bot/tasks/commands.py:378)
at wrapper (/mnt/scratch0/clusterfuzz/src/python/bot/tasks/commands.py:150)
at task_loop (/mnt/scratch0/clusterfuzz/src/python/bot/startup/run_bot.py:99)

* Fix Python 3 bots to use pipenv run, as python3.7 is not inherited. (#1644)

python3.7 call on run.py still causes python 2 to be loaded on
run_bot.py, which is the child process. Use "pipenv run" instead.

* Revert "Fix Python 3 bots to use pipenv run, as python3.7 is not inherited. (#1644)" (#1646)

This reverts commit 01d6c3b1fd60369f6621fa366f93fa422e0ed808.

* Fix exception in deps_to_revisions_dict. (#1645)

* Fix logs test when run locally. (#1639)

* Use sys.executable for invoking Python interpreter. (#1647)

* Simplify tensorflow Pipfile dependency. (#1638)

* Fix source updating on Python 3. (#1649)

* Fix Python 3 exception on Windows. (#1650)

* Increase test timeout. (#1652)

* Exception fixes. (#1653)

* Exception fixes.

- Club blackbox fuzzer exception into one by putting name and
  return code at end of message.
- Fix exception in impact task with production build revision
  a string and not an int.

* Lint fixes.

* Invoke blackbox fuzzers with Python 2 explicitly.

* Break up oddly formatted line

* Temporarily disable this on Windows.

* Rebase and address review comments.

* Work around lint errors

Co-authored-by: Abhishek Arya <inferno@chromium.org>
Co-authored-by: Oliver Chang <oliverchang@users.noreply.github.com>
Co-authored-by: mpherman2 <58443548+mpherman2@users.noreply.github.com>