Fix TypeError exception in leak_blacklist.py (#1663)
Fixes:
```
TypeError: a bytes-like object is required, not 'str'
at create_empty_local_blacklist (/mnt/scratch0/bots/oss-fuzz-linux-zone1-host-3-qq49-8/clusterfuzz/src/python/fuzzing/leak_blacklist.py:44)
at execute_task (/mnt/scratch0/bots/oss-fuzz-linux-zone1-host-3-qq49-8/clusterfuzz/src/python/bot/tasks/analyze_task.py:108)
at run_command (/mnt/scratch0/bots/oss-fuzz-linux-zone1-host-3-qq49-8/clusterfuzz/src/python/bot/tasks/commands.py:204)
at process_command (/mnt/scratch0/bots/oss-fuzz-linux-zone1-host-3-qq49-8/clusterfuzz/src/python/bot/tasks/commands.py:378)
at wrapper (/mnt/scratch0/bots/oss-fuzz-linux-zone1-host-3-qq49-8/clusterfuzz/src/python/bot/tasks/commands.py:150)
at task_loop (/mnt/scratch0/bots/oss-fuzz-linux-zone1-host-3-qq49-8/clusterfuzz/src/python/bot/startup/run_bot.py:99)
```