Cast `reproducer_path` as a `str` from `PosixPath` (#2820)
`engine.Crash()` expects the `reproducer_path` to be a `str` instead of
`Path`.
This was not captured by the test cases but was discovered via this
error after deployment:
```
TypeError: PosixPath('/path/to/inputs/fuzzer-testcases/1489f923c4dca729178b3e3233458550d8d has type PosixPath, but expected one of: bytes, unicode
```