Revert "Chore/py37 proto bump reattempt (#4062)" (#4064)
This reverts commit 7e57e8821d35ec2b12c957239ae75c9bf33964f7.

New error:
```
AttributeError: Unknown field for InstancePolicy: boot_disk

at .__setattr__ ( /mnt/scratch0/clusterfuzz/src/third_party/proto/message.py:932 )
at ._get_allocation_policy ( /mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/google_cloud_utils/batch.py:182 )
at ._create_job ( /mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/google_cloud_utils/batch.py:225 )
at .create_uworker_main_batch_jobs ( /mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/google_cloud_utils/batch.py:139 )
at .schedule_utask_mains ( /mnt/scratch0/clusterfuzz/src/python/bot/startup/run_bot.py:105 )
at .task_loop ( /mnt/scratch0/clusterfuzz/src/python/bot/startup/run_bot.py:136 )
```