Attempting to bump proto/grpcio in Python 3.7 - 3rd attempt (#4066)
### Motivation

Last attempted was
[reverted](https://github.com/google/clusterfuzz/pull/4064) due to an
issue in utask main scheduler, related to protos and gcp batch

This PR attempts to fix the following issue:

```
AttributeError: Unknown field for InstancePolicy: boot_disk

at .__setattr__ ( /mnt/scratch0/clusterfuzz/src/third_party/proto/message.py:932 )
at ._get_allocation_policy ( /mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/google_cloud_utils/batch.py:182 )
at ._create_job ( /mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/google_cloud_utils/batch.py:225 )
at .create_uworker_main_batch_jobs ( /mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/google_cloud_utils/batch.py:139 )
at .schedule_utask_mains ( /mnt/scratch0/clusterfuzz/src/python/bot/startup/run_bot.py:105 )
at .task_loop ( /mnt/scratch0/clusterfuzz/src/python/bot/startup/run_bot.py:136 )
```

### Testing strategy

This issue was caused because batch was set to 0.2.0, and the boot_disk
proto field was only [introduced in
0.6.0](https://cloud.google.com/python/docs/reference/batch/latest/changelog).
Returning the dependency to 0.11.0 solved the issue. This was tested
manually through
[use_batch.py](https://github.com/google/clusterfuzz/blob/bcae6b19f399a74ca105404284a2cad8e174627e/src/clusterfuzz/_internal/tests/core/google_cloud_utils/use_batch.py#L4),
pointing to our internal gcp service.

Evidence that a batch job is successfully created:


![image](https://github.com/google/clusterfuzz/assets/5733577/85b8c476-e1c0-4e89-b5ce-3c2d0d1cc578)


![image](https://github.com/google/clusterfuzz/assets/5733577/39469891-0a5c-4d66-ae81-c12240a08c6f)