Fix UI form parsing that created invalid FuzzerJob entries (#5381)
The `/jobs` form submission retrieved `'fuzzers'` as a string and
blindly called .split(','), meaning an empty field evaluated as `['']`
instead of `[]`.

I tested in dev and the browser is actually sending a POST with the
`fuzzer` key, i.e. `...&fuzzers=&description=...` which results in an
empty string `fuzzers= ""` in Flask . Since there is a value `""`, this
overrides the default `[]`

This fuzzers value of `['']` leads to the creation of invalid
`FuzzerJob` entries in Datastore with `fuzzer=""`

This updates the form ingestion to correctly ignore missing values as an
empty list.

## Testing

I verified this with the unit test by reverting the PR back to the old
behavior:
```
Traceback (most recent call last):
  File "/workspaces/clusterfuzz/src/clusterfuzz/_internal/tests/appengine/handlers/jobs_test.py", line 240, in test_post_empty_fuzzers
    self.mock.update_mappings_for_job.assert_called_with(mock.ANY, [])
  File "/usr/local/python/current/lib/python3.11/unittest/mock.py", line 212, in assert_called_with
    return mock.assert_called_with(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/current/lib/python3.11/unittest/mock.py", line 939, in assert_called_with
    raise AssertionError(_error_message()) from cause
AssertionError: expected call not found.
Expected: update_mappings_for_job(<ANY>, [])
  Actual: update_mappings_for_job(Job(key=Key('Job', 1), base_os_version=None, custom_binary_filename=None, custom_binary_key=None, custom_binary_revision=None, description='', environment_string='', external_reproduction_topic=None, external_updates_subscription=None, keywords=['job', 'test_job', 'test', 'project', 'test-project'], name='test_job', platform='LINUX', project='test-project', templates=[]), [''])
```

The last parameter in the assert is the fuzzers `['']`. We're passing an
empty string into the list of fuzzers to map to the job

dev:
- [x]  Verify in dev via the Jobs UI
1. Create a FuzzerJob in dev by enabling the `libfuzzer` `Fuzzer` on the
`libfuzzer_chrome_asan_highend` job in dev.
2. Disable the `Fuzzer` by unchecking `libfuzzer`, then querying the
Datastore to verify no dangling `FuzzerJob` was created with `fuzzer=''`
`SELECT * FROM `FuzzerJob` where job = 'libfuzzer_chrome_asan_highend'`