Print actual error on unittest import failure (#3181)
Instead of getting meaningless errors like this:
```
Traceback (most recent call last):                                                                                                           
  File "src/local/butler/py_unittest.py", line 160, in run_tests_parallel
    for test_class in subsuite._tests:  # pylint: disable=protected-access                                                                                                                                                                                                                
  File "/usr/local/lib/python3.7/unittest/loader.py", line 32, in __getattr__
    return super(_FailedTest, self).__getattr__(name)          
AttributeError: 'super' object has no attribute '__getattr__'
```