[BlackboxBenchmarking] Remove dry run arg from aggregate_fuzzer_stats cron (#5271)
removes dry run args and makes args optional in `aggregate_fuzzer_stats`
cron job

The bot version of
[run_cron.py](https://github.com/google/clusterfuzz/blob/47ed79626d0fb4fc873f3e4c4646f5fdda6a9630/src/python/bot/startup/run_cron.py#L68)
does not accept any args, while the [local
run_cron.py](https://github.com/google/clusterfuzz/blob/47ed79626d0fb4fc873f3e4c4646f5fdda6a9630/src/local/butler/scripts/run_cron.py#L96)
does accept args.

I previously used required args and this caused the cron job to fail in
dev after I pushed the helm config.

```
Unhandled exception in cron: main() missing 1 required positional argument: 'argv'
Traceback (most recent call last):
  File "/mnt/scratch0/clusterfuzz/src/python/bot/startup/run_cron.py", line 68, in main
    return 0 if task_module.main() else 1
                ^^^^^^^^^^^^^^^^^^
TypeError: main() missing 1 required positional argument: 'argv'
```