Removing build-failure label from oss-fuzz-build-status (#4292)
This label does not exist anymore, given the monorail-buganizer data
mapping, and is causing oss-fuzz-build-status cron to error out,
avoiding new bugs being opened:

```
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://issuetracker.googleapis.com/v1/issues?templateOptions.applyTemplate=true&alt=json returned "Invalid value at 'issue.issue_state.type' (type.googleapis.com/google.devtools.issuetracker.v1.Issue.Type), "Build-Failure"". Details: "[{'@type': 'type.googleapis.com/google.rpc.BadRequest', 'fieldViolations': [{'field': 'issue.issue_state.type', 'description': 'Invalid value at \'issue.issue_state.type\' (type.googleapis.com/google.devtools.issuetracker.v1.Issue.Type), "Build-Failure"'}]}]">
```