Fix downloading corpus backup. (#4817)
Some fuzzers (centipede in Chrome) might not have a backup bucket, don't
attempt anything here.
list_blobs is not ideal for checking the existence of a file because it
retries in some cases when you want it to return immediately (e.g.
gs://None/blah/blah). Use exists() instead and call list_blobs again
(this probably has an acceptable performance cost).

This was the error (with the retry wrapper removed):
```
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://storage.googleapis.com/storage/v1/b/None/o/corpus%2Fcentipede%2Fv8_reg_exp_two_byte_run_reg_exp_fuzztest%2Flatest.zip?alt=json returned "Invalid bucket name: 'None'". Details: "[{'message': "Invalid bucket name: 'None'", 'domain': 'global', 'reason': 'invalid'}]">

at .execute ( /home/user/clusterfuzz/src/appengine/third_party/googleapiclient/http.py:938 )
at .positional_wrapper ( /home/user/clusterfuzz/src/appengine/third_party/googleapiclient/_helpers.py:130 )
at .get ( /home/user/clusterfuzz/src/clusterfuzz/_internal/google_cloud_utils/storage.py:420 )
at .exists ( /home/user/clusterfuzz/src/clusterfuzz/_internal/google_cloud_utils/storage.py:1042 )
```