Revert "centipede: keep batch_size during minimization (#4767)" (#4772)
This reverts commit bcd1f40a500ef2e01ef325f954c5040394d0c55c.

Causes:
https://pantheon.corp.google.com/errors/detail/CPTcoNzgs-WiHw;locations=global?project=google.com:clusterfuzz

TypeError: '<' not supported between instances of 'int' and 'str' at
.minimize_corpus (
/mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/bot/fuzzers/centipede/engine.py:502
) at .fuzz (
/mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/bot/fuzzers/centipede/engine.py:357
)