Make untrusted_host use timestamps instead of dates (#4181)
It's simpler to use timestamps with protos, and we've been doing this
already in chrome and internal google.
Fixes:
https://pantheon.corp.google.com/errors/detail/CM3Hppa8wfSgCQ;time=PT6H;locations=global?e=-13802955&mods=logs_tg_prod&project=clusterfuzz-external
```

AttributeError: 'datetime.date' object has no attribute 'utctimetuple'

at .FromDatetime ( /mnt/scratch0/bots/oss-fuzz-linux-zone5-host-9xqb-0/clusterfuzz/src/third_party/google/protobuf/internal/well_known_types.py:270 )
at ._extract_coverage_information ( /mnt/scratch0/bots/oss-fuzz-linux-zone5-host-9xqb-0/clusterfuzz/src/clusterfuzz/_internal/bot/tasks/utasks/corpus_pruning_task.py:960 )
at .utask_main ( /mnt/scratch0/bots/oss-fuzz-linux-zone5-host-9xqb-0/clusterfuzz/src/clusterfuzz/_internal/bot/tasks/utasks/corpus_pruning_task.py:1024 )
```