Fix exception when stacktrace is not generated for Honggfuzz crashes.
Should fix
```
AttributeError: 'NoneType' object has no attribute 'splitlines'
at process_stacktrace (/mnt/scratch0/clusterfuzz/src/python/crash_analysis/stack_parsing/stack_symbolizer.py:489)
at symbolize_stacktrace (/mnt/scratch0/clusterfuzz/src/python/crash_analysis/stack_parsing/stack_symbolizer.py:636)
at get_crash_data (/mnt/scratch0/clusterfuzz/src/python/crash_analysis/stack_parsing/stack_analyzer.py:1149)
at __init__ (/mnt/scratch0/clusterfuzz/src/python/bot/tasks/fuzz_task.py:202)
at from_engine_crash (/mnt/scratch0/clusterfuzz/src/python/bot/tasks/fuzz_task.py:174)
at do_engine_fuzzing (/mnt/scratch0/clusterfuzz/src/python/bot/tasks/fuzz_task.py:1605)
at run (/mnt/scratch0/clusterfuzz/src/python/bot/tasks/fuzz_task.py:1863)
at execute_task (/mnt/scratch0/clusterfuzz/src/python/bot/tasks/fuzz_task.py:1943)
at run_command (/mnt/scratch0/clusterfuzz/src/python/bot/tasks/commands.py:204)
at process_command (/mnt/scratch0/clusterfuzz/src/python/bot/tasks/commands.py:378)
at wrapper (/mnt/scratch0/clusterfuzz/src/python/bot/tasks/commands.py:150)
at task_loop (/mnt/scratch0/clusterfuzz/src/python/bot/startup/run_bot.py:99)
```

Use an empty stack when not available instead of None.