Fix issues in ClusterFuzz (#4079)
The following issues have been fixed:
1. TypeError: 'in <string>' requires string as left operand, not
NoneType
2. TypeError: '>' not supported between instances of 'NoneType' and
'int'
3. Failed to parse logcat line: (11285): strips
4. AttributeError: 'NoneType' object has no attribute 'update'
5. AttributeError: 'bool' object has no attribute 'endswith'