Remove unnecessary strip causing exceptions (#57)
AttributeError: 'NoneType' object has no attribute 'strip'
at post (/base/data/home/apps/s~cluster-fuzz/20190202t044434.415828721241012675/handlers/fuzzers.py:214)