Added Debugging Logs:
Logs have been added to debug and resolve the following issues:
1. OSError: [Error 28] No space left on device
2. AttributeError: 'NoneType' object has no attribute 'stdin'
3. Line is too long for a stacktrace